version: '3.7'
### Minimum v3.7 required for 'init: true'

services:
  unbound:
    image: iamgavinj/unbound-pymod:latest
    container_name: unbound
    init: true
    network_mode: bridge
    restart: always
    volumes:
      - /docker/unbound/etc:/usr/local/etc/unbound
      - /docker/unbound/log:/var/log/unbound
      - /docker/unbound/run:/var/run/unbound
    ports:
      - "53:53"
      - "53:53/udp"
