version: '3.7'

services:
  unbound:
    image: iamgavinj/unbound:latest
    container_name: unbound
    init: true
    network_mode: bridge
    restart: always
    volumes:
      - /docker/unbound/etc:/usr/local/etc/unbound
      - /docker/unbound/log:/var/log/unbound
      - /docker/unbound/run:/var/run/unbound
    ports:
      - "53:53"
      - "53:53/udp"
